'use client';

import { ChangeEvent, useEffect, useRef, useState } from 'react';
import Link from 'next/link';
import { BarChart3, Boxes, Check, ChevronLeft, CircleDollarSign, Download, LayoutDashboard, Minus, Moon, Plus, ReceiptText, Search, Settings, ShoppingCart, Sun, Trash2, Upload, Users } from 'lucide-react';
import { Button } from '@/app/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/app/components/ui/card';
import { Input } from '@/app/components/ui/input';
import { Label } from '@/app/components/ui/label';

type Tab = 'dashboard' | 'caisse' | 'stock' | 'depenses' | 'credits' | 'rapports' | 'reglages';
type Product = { id: string; name: string; category: string; price: number; stock: number; alert: number };
type Sale = { id: string; date: string; total: number; items: { name: string; quantity: number; total: number }[] };
type Expense = { id: string; date: string; label: string; amount: number };
type Credit = { id: string; customer: string; phone: string; amount: number; paid: boolean; date: string };
type Data = { products: Product[]; sales: Sale[]; expenses: Expense[]; credits: Credit[]; barName: string };
const STORAGE_KEY = 'bar-pilot-local-v1';
const seed: Data = { barName: 'Mon Bar', products: [
  { id: 'regab', name: 'Régab 65 cl', category: 'Bière', price: 1500, stock: 48, alert: 12 },
  { id: 'beaufort', name: 'Beaufort 50 cl', category: 'Bière', price: 2000, stock: 30, alert: 10 },
  { id: 'castel', name: 'Castel Beer', category: 'Bière', price: 1500, stock: 24, alert: 8 },
  { id: 'coca', name: 'Coca-Cola', category: 'Soda', price: 1000, stock: 36, alert: 10 },
  { id: 'eau', name: 'Andza', category: 'Eau', price: 500, stock: 60, alert: 12 },
  { id: 'whisky', name: 'Whisky — verre', category: 'Spiritueux', price: 2500, stock: 18, alert: 5 },
], sales: [], expenses: [], credits: [], };
const money = (n: number) => `${Math.round(n).toLocaleString('fr-FR')} FCFA`;
const today = () => new Date().toISOString();
const nav = [
  { id: 'dashboard' as Tab, label: 'Aperçu', icon: LayoutDashboard }, { id: 'caisse' as Tab, label: 'Caisse', icon: ShoppingCart }, { id: 'stock' as Tab, label: 'Stock', icon: Boxes }, { id: 'depenses' as Tab, label: 'Dépenses', icon: ReceiptText }, { id: 'credits' as Tab, label: 'Crédits', icon: Users }, { id: 'rapports' as Tab, label: 'Rapports', icon: BarChart3 }, { id: 'reglages' as Tab, label: 'Réglages', icon: Settings },
];

export default function OfflinePage() {
  const [data, setData] = useState<Data>(seed); const [ready, setReady] = useState(false); const [tab, setTab] = useState<Tab>('dashboard'); const [dark, setDark] = useState(false); const [cart, setCart] = useState<Record<string, number>>({}); const [query, setQuery] = useState(''); const fileRef = useRef<HTMLInputElement>(null);
  // Hydrate once from this device before persisting subsequent changes.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { try { const saved = localStorage.getItem(STORAGE_KEY); if (saved) setData(JSON.parse(saved)); } catch {} setReady(true); }, []);
  useEffect(() => { if (ready) localStorage.setItem(STORAGE_KEY, JSON.stringify(data)); }, [data, ready]);
  const salesToday = data.sales.filter((s) => new Date(s.date).toDateString() === new Date().toDateString()); const revenue = salesToday.reduce((s, v) => s + v.total, 0); const expenses = data.expenses.reduce((s, v) => s + v.amount, 0); const debt = data.credits.filter((c) => !c.paid).reduce((s, v) => s + v.amount, 0); const low = data.products.filter((p) => p.stock <= p.alert); const cartLines = data.products.filter((p) => cart[p.id]).map((p) => ({ ...p, quantity: cart[p.id] })); const cartTotal = cartLines.reduce((s, p) => s + p.price * p.quantity, 0);
  const add = (p: Product) => setCart((c) => ({ ...c, [p.id]: Math.min(p.stock, (c[p.id] || 0) + 1) }));
  const checkout = () => { if (!cartLines.length) return; const sale: Sale = { id: crypto.randomUUID(), date: today(), total: cartTotal, items: cartLines.map((p) => ({ name: p.name, quantity: p.quantity, total: p.price * p.quantity })) }; setData((d) => ({ ...d, sales: [sale, ...d.sales], products: d.products.map((p) => ({ ...p, stock: p.stock - (cart[p.id] || 0) })) })); setCart({}); alert(`Vente enregistrée : ${money(cartTotal)}`); };
  const exportData = () => { const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' }); const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = `bar-pilot-${new Date().toISOString().slice(0, 10)}.json`; a.click(); URL.revokeObjectURL(url); };
  const importData = async (e: ChangeEvent<HTMLInputElement>) => { const file = e.target.files?.[0]; if (!file) return; try { const parsed = JSON.parse(await file.text()); if (!Array.isArray(parsed.products) || !Array.isArray(parsed.sales)) throw new Error(); setData(parsed); alert('Sauvegarde restaurée.'); } catch { alert('Ce fichier de sauvegarde est invalide.'); } };
  if (!ready) return <div className="flex min-h-screen items-center justify-center">Ouverture du gestionnaire local…</div>;

  return <div className={dark ? 'dark' : ''}><main className="min-h-screen bg-background text-foreground"><div className="flex min-h-screen flex-col md:flex-row">
    <aside className="border-b bg-sidebar text-sidebar-foreground md:sticky md:top-0 md:h-screen md:w-64 md:border-b-0 md:p-4"><div className="flex items-center justify-between p-3 md:mb-6"><div className="flex items-center gap-3"><span className="flex size-10 items-center justify-center rounded-xl bg-sidebar-primary font-mono text-sm font-bold text-sidebar-primary-foreground">BP</span><div><p className="font-heading font-semibold">{data.barName}</p><p className="text-xs text-sidebar-foreground/55">Mode local</p></div></div><Button size="icon" variant="ghost" aria-label="Changer de thème" onClick={() => setDark(!dark)}>{dark ? <Sun /> : <Moon />}</Button></div><nav className="flex gap-1 overflow-x-auto p-2 md:flex-col md:p-0">{nav.map(({ id, label, icon: Icon }) => <button key={id} onClick={() => setTab(id)} className={`flex shrink-0 items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-medium transition ${tab === id ? 'bg-sidebar-primary text-sidebar-primary-foreground' : 'text-sidebar-foreground/65 hover:bg-sidebar-accent hover:text-sidebar-accent-foreground'}`}><Icon className="size-5" />{label}</button>)}</nav><Link href="/" className="m-2 hidden items-center gap-2 rounded-xl px-3 py-2.5 text-sm text-sidebar-foreground/65 hover:bg-sidebar-accent md:flex"><ChevronLeft className="size-4" />Retour à l’accueil</Link></aside>
    <section className="min-w-0 flex-1 bg-muted/35 p-4 md:p-8"><div className="mx-auto flex max-w-7xl flex-col gap-6"><header><p className="font-mono text-xs font-bold uppercase tracking-[.18em] text-primary">{new Date().toLocaleDateString('fr-FR', { weekday: 'long', day: 'numeric', month: 'long' })}</p><h1 className="mt-2 font-heading text-3xl font-bold">{nav.find((n) => n.id === tab)?.label}</h1></header>

    {tab === 'dashboard' && <><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Stat label="Recette du jour" value={money(revenue)} icon={CircleDollarSign} /><Stat label="Ventes" value={String(salesToday.length)} icon={ShoppingCart} /><Stat label="Crédits ouverts" value={money(debt)} icon={Users} /><Stat label="Alertes stock" value={String(low.length)} icon={Boxes} /></div><div className="grid gap-4 lg:grid-cols-2"><Card><CardHeader><CardTitle>Activité récente</CardTitle><CardDescription>Les dernières ventes enregistrées sur cet appareil.</CardDescription></CardHeader><CardContent>{data.sales.length ? <div className="flex flex-col gap-3">{data.sales.slice(0, 5).map((s) => <div key={s.id} className="flex items-center justify-between border-b pb-3"><div><p className="font-medium">{s.items.map((i) => i.name).join(', ')}</p><p className="text-xs text-muted-foreground">{new Date(s.date).toLocaleString('fr-FR')}</p></div><strong className="font-mono">{money(s.total)}</strong></div>)}</div> : <Empty text="Votre première vente apparaîtra ici." />}</CardContent></Card><Card><CardHeader><CardTitle>Stock à surveiller</CardTitle><CardDescription>Produits arrivés au seuil d’alerte.</CardDescription></CardHeader><CardContent>{low.length ? <div className="flex flex-col gap-3">{low.map((p) => <div key={p.id} className="flex items-center justify-between rounded-xl bg-destructive/10 p-3"><span className="font-medium">{p.name}</span><span className="font-mono text-sm text-destructive">{p.stock} restant(s)</span></div>)}</div> : <Empty text="Tous les niveaux sont corrects." />}</CardContent></Card></div></>}

    {tab === 'caisse' && <div className="grid gap-4 xl:grid-cols-[1fr_380px]"><Card><CardHeader><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><CardTitle>Produits</CardTitle><CardDescription>Sélection tactile rapide</CardDescription></div><label className="relative"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" /><span className="sr-only">Rechercher</span><Input className="pl-9" value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Rechercher…" /></label></div></CardHeader><CardContent><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{data.products.filter((p) => `${p.name} ${p.category}`.toLowerCase().includes(query.toLowerCase())).map((p) => <button key={p.id} disabled={!p.stock} onClick={() => add(p)} className="flex min-h-32 flex-col justify-between rounded-2xl border bg-background p-4 text-left transition hover:border-primary disabled:opacity-40"><div><p className="font-semibold">{p.name}</p><p className="text-sm text-muted-foreground">{p.category}</p></div><div className="flex items-end justify-between"><strong className="font-mono text-primary">{money(p.price)}</strong><span className="text-xs text-muted-foreground">{p.stock}</span></div></button>)}</div></CardContent></Card><Card className="h-fit xl:sticky xl:top-6"><CardHeader><CardTitle>Commande</CardTitle><CardDescription>{cartLines.reduce((s, p) => s + p.quantity, 0)} article(s)</CardDescription></CardHeader><CardContent><div className="flex flex-col gap-4">{cartLines.length ? cartLines.map((p) => <div key={p.id} className="flex items-center justify-between border-b pb-3"><div><p className="font-medium">{p.name}</p><p className="font-mono text-xs text-muted-foreground">{money(p.price * p.quantity)}</p></div><div className="flex items-center gap-1"><Button size="icon" variant="outline" onClick={() => setCart((c) => ({ ...c, [p.id]: Math.max(0, c[p.id] - 1) }))}><Minus /></Button><span className="w-6 text-center">{p.quantity}</span><Button size="icon" variant="outline" onClick={() => add(p)}><Plus /></Button></div></div>) : <Empty text="Le panier est vide." />}<div className="flex justify-between text-xl font-bold"><span>Total</span><span>{money(cartTotal)}</span></div><Button size="lg" disabled={!cartLines.length} onClick={checkout}><Check data-icon="inline-start" />Encaisser</Button></div></CardContent></Card></div>}

    {tab === 'stock' && <Stock data={data} setData={setData} />}
    {tab === 'depenses' && <Expenses data={data} setData={setData} />}
    {tab === 'credits' && <Credits data={data} setData={setData} />}
    {tab === 'rapports' && <Reports data={data} expenses={expenses} />}
    {tab === 'reglages' && <Card><CardHeader><CardTitle>Réglages et sauvegarde</CardTitle><CardDescription>Vos données restent sur cet appareil. Exportez-les régulièrement.</CardDescription></CardHeader><CardContent><div className="flex max-w-xl flex-col gap-6"><label className="flex flex-col gap-2"><Label>Nom du bar</Label><Input value={data.barName} onChange={(e) => setData({ ...data, barName: e.target.value })} /></label><div className="flex flex-wrap gap-3"><Button onClick={exportData}><Download data-icon="inline-start" />Exporter JSON</Button><Button variant="outline" onClick={() => fileRef.current?.click()}><Upload data-icon="inline-start" />Importer</Button><input ref={fileRef} className="sr-only" type="file" accept="application/json" onChange={importData} /></div><Button variant="destructive" onClick={() => { if (confirm('Effacer toutes les données locales ?')) { setData(seed); setCart({}); } }}><Trash2 data-icon="inline-start" />Réinitialiser les données</Button></div></CardContent></Card>}
    </div></section></div></main></div>;
}

function Stat({ label, value, icon: Icon }: { label: string; value: string; icon: typeof ShoppingCart }) { return <div className="flex items-center gap-4 rounded-2xl border bg-card p-4"><span className="flex size-11 items-center justify-center rounded-xl bg-secondary text-primary"><Icon className="size-5" /></span><div className="min-w-0"><p className="text-xs uppercase tracking-wide text-muted-foreground">{label}</p><p className="truncate font-heading text-xl font-bold">{value}</p></div></div> }
function Empty({ text }: { text: string }) { return <p className="rounded-xl bg-muted p-6 text-center text-sm text-muted-foreground">{text}</p> }
function Stock({ data, setData }: { data: Data; setData: (d: Data) => void }) { const [form, setForm] = useState({ name: '', category: '', price: '', stock: '', alert: '5' }); const submit = (e: React.FormEvent) => { e.preventDefault(); if (!form.name || !form.price) return; setData({ ...data, products: [...data.products, { id: crypto.randomUUID(), name: form.name, category: form.category || 'Autre', price: Number(form.price), stock: Number(form.stock || 0), alert: Number(form.alert || 5) }] }); setForm({ name: '', category: '', price: '', stock: '', alert: '5' }); }; return <div className="grid gap-4 lg:grid-cols-[360px_1fr]"><Card><CardHeader><CardTitle>Nouveau produit</CardTitle><CardDescription>Ajoutez une référence locale.</CardDescription></CardHeader><CardContent><form onSubmit={submit} className="flex flex-col gap-4">{(['name','category','price','stock','alert'] as const).map((key) => <label key={key} className="flex flex-col gap-2"><Label>{({name:'Nom',category:'Catégorie',price:'Prix FCFA',stock:'Stock initial',alert:'Seuil d’alerte'} as const)[key]}</Label><Input type={['price','stock','alert'].includes(key) ? 'number' : 'text'} value={form[key]} onChange={(e) => setForm({ ...form, [key]: e.target.value })} /></label>)}<Button type="submit"><Plus data-icon="inline-start" />Ajouter</Button></form></CardContent></Card><Card><CardHeader><CardTitle>Inventaire</CardTitle><CardDescription>{data.products.length} références</CardDescription></CardHeader><CardContent><div className="flex flex-col gap-2">{data.products.map((p) => <div key={p.id} className="flex items-center justify-between gap-3 rounded-xl border p-3"><div><p className="font-medium">{p.name}</p><p className="text-xs text-muted-foreground">{money(p.price)} · seuil {p.alert}</p></div><div className="flex items-center gap-2"><Input aria-label={`Stock de ${p.name}`} className="w-20" type="number" value={p.stock} onChange={(e) => setData({ ...data, products: data.products.map((x) => x.id === p.id ? { ...x, stock: Number(e.target.value) } : x) })} /><Button size="icon" variant="ghost" aria-label={`Supprimer ${p.name}`} onClick={() => setData({ ...data, products: data.products.filter((x) => x.id !== p.id) })}><Trash2 /></Button></div></div>)}</div></CardContent></Card></div> }
function Expenses({ data, setData }: { data: Data; setData: (d: Data) => void }) { const [label, setLabel] = useState(''); const [amount, setAmount] = useState(''); return <Card><CardHeader><CardTitle>Dépenses</CardTitle><CardDescription>Achats, transport, personnel et charges.</CardDescription></CardHeader><CardContent><form className="mb-6 flex flex-col gap-3 sm:flex-row" onSubmit={(e) => { e.preventDefault(); if (!label || !amount) return; setData({ ...data, expenses: [{ id: crypto.randomUUID(), label, amount: Number(amount), date: today() }, ...data.expenses] }); setLabel(''); setAmount(''); }}><Input value={label} onChange={(e) => setLabel(e.target.value)} placeholder="Libellé" /><Input type="number" value={amount} onChange={(e) => setAmount(e.target.value)} placeholder="Montant FCFA" /><Button type="submit"><Plus data-icon="inline-start" />Ajouter</Button></form><div className="flex flex-col gap-2">{data.expenses.map((x) => <div key={x.id} className="flex items-center justify-between rounded-xl border p-3"><div><p className="font-medium">{x.label}</p><p className="text-xs text-muted-foreground">{new Date(x.date).toLocaleDateString('fr-FR')}</p></div><strong className="font-mono">{money(x.amount)}</strong></div>)}{!data.expenses.length && <Empty text="Aucune dépense enregistrée." />}</div></CardContent></Card> }
function Credits({ data, setData }: { data: Data; setData: (d: Data) => void }) { const [customer, setCustomer] = useState(''); const [amount, setAmount] = useState(''); return <Card><CardHeader><CardTitle>Crédits clients</CardTitle><CardDescription>Suivez les ardoises et marquez les remboursements.</CardDescription></CardHeader><CardContent><form className="mb-6 flex flex-col gap-3 sm:flex-row" onSubmit={(e) => { e.preventDefault(); if (!customer || !amount) return; setData({ ...data, credits: [{ id: crypto.randomUUID(), customer, phone: '', amount: Number(amount), paid: false, date: today() }, ...data.credits] }); setCustomer(''); setAmount(''); }}><Input value={customer} onChange={(e) => setCustomer(e.target.value)} placeholder="Nom du client" /><Input type="number" value={amount} onChange={(e) => setAmount(e.target.value)} placeholder="Montant FCFA" /><Button type="submit"><Plus data-icon="inline-start" />Ajouter</Button></form><div className="flex flex-col gap-2">{data.credits.map((x) => <div key={x.id} className="flex items-center justify-between gap-3 rounded-xl border p-3"><div><p className={x.paid ? 'font-medium line-through opacity-55' : 'font-medium'}>{x.customer}</p><p className="font-mono text-sm text-muted-foreground">{money(x.amount)}</p></div><Button variant={x.paid ? 'outline' : 'default'} onClick={() => setData({ ...data, credits: data.credits.map((c) => c.id === x.id ? { ...c, paid: !c.paid } : c) })}>{x.paid ? 'Rouvrir' : 'Marquer payé'}</Button></div>)}{!data.credits.length && <Empty text="Aucun crédit en cours." />}</div></CardContent></Card> }
function Reports({ data, expenses }: { data: Data; expenses: number }) { const total = data.sales.reduce((s, x) => s + x.total, 0); const counts = data.sales.flatMap((s) => s.items).reduce<Record<string, number>>((a, x) => ({ ...a, [x.name]: (a[x.name] || 0) + x.quantity }), {}); const best = Object.entries(counts).sort((a,b) => b[1]-a[1]).slice(0,5); return <><div className="grid gap-3 sm:grid-cols-3"><Stat label="Ventes cumulées" value={money(total)} icon={BarChart3} /><Stat label="Dépenses cumulées" value={money(expenses)} icon={ReceiptText} /><Stat label="Solde estimé" value={money(total-expenses)} icon={CircleDollarSign} /></div><Card><CardHeader><CardTitle>Meilleures ventes</CardTitle><CardDescription>Classement par quantité vendue.</CardDescription></CardHeader><CardContent>{best.length ? <div className="flex flex-col gap-3">{best.map(([name,count], i) => <div key={name} className="flex items-center gap-3"><span className="flex size-8 items-center justify-center rounded-lg bg-secondary font-mono text-xs font-bold text-primary">{i+1}</span><span className="flex-1 font-medium">{name}</span><strong>{count}</strong></div>)}</div> : <Empty text="Encaissez des ventes pour générer le rapport." />}</CardContent></Card></> }
